import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Contact',
}

export default function Page() {
  return <h1>Contact section
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec est purus. Ut tincidunt et arcu ac pulvinar. Proin rutrum a ex sit amet accumsan. Pellentesque at orci lectus. Praesent condimentum lacus vel ligula sodales ultricies. Praesent ornare ullamcorper ligula, eget euismod diam malesuada ullamcorper. Vivamus leo tellus, molestie ut ligula in, feugiat euismod velit. Curabitur turpis enim, tempus vel viverra eu, consequat vitae neque. Praesent consequat ullamcorper egestas. Quisque eros eros, gravida nec turpis nec, condimentum feugiat mi. Morbi sit amet nulla turpis. Donec elit urna, consequat non suscipit ut, egestas id sem. Curabitur et tempor justo. Aenean nec ultricies ipsum. Nullam ipsum lorem, molestie ac nibh id, vestibulum mattis justo. Phasellus consectetur turpis eleifend, malesuada est fermentum, feugiat risus.

Nam congue aliquet blandit. Nulla felis sem, dictum quis condimentum nec, vehicula ut arcu. Vestibulum ac malesuada est. Duis at pulvinar dui, ultrices commodo tellus. Nulla feugiat commodo justo, hendrerit elementum dolor finibus auctor. Aliquam et mi hendrerit, convallis risus vel, pulvinar erat. Mauris elementum turpis ut tempor interdum. Pellentesque sed nunc et sapien aliquet euismod. Curabitur vehicula, ligula placerat feugiat consectetur, urna dolor efficitur nisl, tincidunt finibus sapien mauris et augue. Morbi laoreet quam eget ligula lobortis scelerisque. Donec ut facilisis dui. Cras consectetur interdum imperdiet. Sed ac porta dolor.

Nulla vitae mauris ullamcorper, aliquet leo nec, consectetur ante. Morbi sodales elit at mauris consequat, in bibendum sapien efficitur. Praesent lobortis quam a mollis congue. Donec ante urna, finibus consequat auctor sit amet, dictum eu erat. In aliquam est eu metus efficitur, at malesuada massa gravida. Cras pharetra consequat lacus, sed placerat nunc aliquet in. Proin laoreet massa et risus mollis egestas sit amet eu urna.

Pellentesque mattis nisi sit amet dictum mattis. Integer consectetur facilisis nisi, vitae congue sapien imperdiet ut. Proin sodales nisl justo. Nullam ut elementum mauris, sed vehicula eros. Ut a consequat nibh. Duis ut porttitor tortor. Ut vestibulum nulla ac arcu viverra scelerisque. Aenean odio purus, sagittis ut suscipit vitae, hendrerit nec tellus. Aliquam viverra nunc in tellus aliquam aliquet non id mauris. Praesent dolor risus, viverra vitae lorem fringilla, hendrerit bibendum erat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras luctus neque sit amet quam placerat varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse feugiat tortor ligula, eget elementum augue congue in.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet bibendum urna. Etiam commodo justo quis lectus venenatis venenatis. Nullam eu laoreet dolor, ut finibus velit. Phasellus eu lacus id odio pretium ultrices id id nulla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce sit amet ullamcorper nisl. Phasellus porttitor, velit et tempor pulvinar, diam nulla eleifend purus, a placerat orci dolor a augue. Quisque lectus augue, tincidunt in pellentesque nec, eleifend nec orci. Donec pellentesque at massa in sollicitudin. Nam ultricies felis non quam maximus ultricies. Aenean rutrum tortor tortor, id placerat dui eleifend sed. Praesent eleifend condimentum porta. Proin hendrerit metus in blandit eleifend.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec est purus. Ut tincidunt et arcu ac pulvinar. Proin rutrum a ex sit amet accumsan. Pellentesque at orci lectus. Praesent condimentum lacus vel ligula sodales ultricies. Praesent ornare ullamcorper ligula, eget euismod diam malesuada ullamcorper. Vivamus leo tellus, molestie ut ligula in, feugiat euismod velit. Curabitur turpis enim, tempus vel viverra eu, consequat vitae neque. Praesent consequat ullamcorper egestas. Quisque eros eros, gravida nec turpis nec, condimentum feugiat mi. Morbi sit amet nulla turpis. Donec elit urna, consequat non suscipit ut, egestas id sem. Curabitur et tempor justo. Aenean nec ultricies ipsum. Nullam ipsum lorem, molestie ac nibh id, vestibulum mattis justo. Phasellus consectetur turpis eleifend, malesuada est fermentum, feugiat risus.

Nam congue aliquet blandit. Nulla felis sem, dictum quis condimentum nec, vehicula ut arcu. Vestibulum ac malesuada est. Duis at pulvinar dui, ultrices commodo tellus. Nulla feugiat commodo justo, hendrerit elementum dolor finibus auctor. Aliquam et mi hendrerit, convallis risus vel, pulvinar erat. Mauris elementum turpis ut tempor interdum. Pellentesque sed nunc et sapien aliquet euismod. Curabitur vehicula, ligula placerat feugiat consectetur, urna dolor efficitur nisl, tincidunt finibus sapien mauris et augue. Morbi laoreet quam eget ligula lobortis scelerisque. Donec ut facilisis dui. Cras consectetur interdum imperdiet. Sed ac porta dolor.

Nulla vitae mauris ullamcorper, aliquet leo nec, consectetur ante. Morbi sodales elit at mauris consequat, in bibendum sapien efficitur. Praesent lobortis quam a mollis congue. Donec ante urna, finibus consequat auctor sit amet, dictum eu erat. In aliquam est eu metus efficitur, at malesuada massa gravida. Cras pharetra consequat lacus, sed placerat nunc aliquet in. Proin laoreet massa et risus mollis egestas sit amet eu urna.

Pellentesque mattis nisi sit amet dictum mattis. Integer consectetur facilisis nisi, vitae congue sapien imperdiet ut. Proin sodales nisl justo. Nullam ut elementum mauris, sed vehicula eros. Ut a consequat nibh. Duis ut porttitor tortor. Ut vestibulum nulla ac arcu viverra scelerisque. Aenean odio purus, sagittis ut suscipit vitae, hendrerit nec tellus. Aliquam viverra nunc in tellus aliquam aliquet non id mauris. Praesent dolor risus, viverra vitae lorem fringilla, hendrerit bibendum erat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras luctus neque sit amet quam placerat varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse feugiat tortor ligula, eget elementum augue congue in.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet bibendum urna. Etiam commodo justo quis lectus venenatis venenatis. Nullam eu laoreet dolor, ut finibus velit. Phasellus eu lacus id odio pretium ultrices id id nulla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce sit amet ullamcorper nisl. Phasellus porttitor, velit et tempor pulvinar, diam nulla eleifend purus, a placerat orci dolor a augue. Quisque lectus augue, tincidunt in pellentesque nec, eleifend nec orci. Donec pellentesque at massa in sollicitudin. Nam ultricies felis non quam maximus ultricies. Aenean rutrum tortor tortor, id placerat dui eleifend sed. Praesent eleifend condimentum porta. Proin hendrerit metus in blandit eleifend.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec est purus. Ut tincidunt et arcu ac pulvinar. Proin rutrum a ex sit amet accumsan. Pellentesque at orci lectus. Praesent condimentum lacus vel ligula sodales ultricies. Praesent ornare ullamcorper ligula, eget euismod diam malesuada ullamcorper. Vivamus leo tellus, molestie ut ligula in, feugiat euismod velit. Curabitur turpis enim, tempus vel viverra eu, consequat vitae neque. Praesent consequat ullamcorper egestas. Quisque eros eros, gravida nec turpis nec, condimentum feugiat mi. Morbi sit amet nulla turpis. Donec elit urna, consequat non suscipit ut, egestas id sem. Curabitur et tempor justo. Aenean nec ultricies ipsum. Nullam ipsum lorem, molestie ac nibh id, vestibulum mattis justo. Phasellus consectetur turpis eleifend, malesuada est fermentum, feugiat risus.

Nam congue aliquet blandit. Nulla felis sem, dictum quis condimentum nec, vehicula ut arcu. Vestibulum ac malesuada est. Duis at pulvinar dui, ultrices commodo tellus. Nulla feugiat commodo justo, hendrerit elementum dolor finibus auctor. Aliquam et mi hendrerit, convallis risus vel, pulvinar erat. Mauris elementum turpis ut tempor interdum. Pellentesque sed nunc et sapien aliquet euismod. Curabitur vehicula, ligula placerat feugiat consectetur, urna dolor efficitur nisl, tincidunt finibus sapien mauris et augue. Morbi laoreet quam eget ligula lobortis scelerisque. Donec ut facilisis dui. Cras consectetur interdum imperdiet. Sed ac porta dolor.

Nulla vitae mauris ullamcorper, aliquet leo nec, consectetur ante. Morbi sodales elit at mauris consequat, in bibendum sapien efficitur. Praesent lobortis quam a mollis congue. Donec ante urna, finibus consequat auctor sit amet, dictum eu erat. In aliquam est eu metus efficitur, at malesuada massa gravida. Cras pharetra consequat lacus, sed placerat nunc aliquet in. Proin laoreet massa et risus mollis egestas sit amet eu urna.

Pellentesque mattis nisi sit amet dictum mattis. Integer consectetur facilisis nisi, vitae congue sapien imperdiet ut. Proin sodales nisl justo. Nullam ut elementum mauris, sed vehicula eros. Ut a consequat nibh. Duis ut porttitor tortor. Ut vestibulum nulla ac arcu viverra scelerisque. Aenean odio purus, sagittis ut suscipit vitae, hendrerit nec tellus. Aliquam viverra nunc in tellus aliquam aliquet non id mauris. Praesent dolor risus, viverra vitae lorem fringilla, hendrerit bibendum erat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras luctus neque sit amet quam placerat varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse feugiat tortor ligula, eget elementum augue congue in.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet bibendum urna. Etiam commodo justo quis lectus venenatis venenatis. Nullam eu laoreet dolor, ut finibus velit. Phasellus eu lacus id odio pretium ultrices id id nulla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce sit amet ullamcorper nisl. Phasellus porttitor, velit et tempor pulvinar, diam nulla eleifend purus, a placerat orci dolor a augue. Quisque lectus augue, tincidunt in pellentesque nec, eleifend nec orci. Donec pellentesque at massa in sollicitudin. Nam ultricies felis non quam maximus ultricies. Aenean rutrum tortor tortor, id placerat dui eleifend sed. Praesent eleifend condimentum porta. Proin hendrerit metus in blandit eleifend.
  </h1>
}
